package br.com.sss.View;

import br.com.sss.model.Empresa;
import br.com.sss.Control.BackupSql;
import br.com.sss.Control.CaminhoImagem;
import br.com.sss.Control.Conexao;
import br.com.sss.Control.ConvertPasswordToMD5;
import br.com.sss.Control.GeraData;
import br.com.sss.Control.ImportaExportaBDExcel;
import br.com.sss.Control.MensagemController;
import br.com.sss.Control.MensagemErro;
import br.com.sss.model.Mensagem;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego Rangel  
 */

public class JanelaConfiguracao extends javax.swing.JInternalFrame {

    CaminhoImagem caminhoImagemIcone = new CaminhoImagem();
    ImportaExportaBDExcel i = new ImportaExportaBDExcel();
    Conexao co = new Conexao();
    ConvertPasswordToMD5 ConverteSenha = new ConvertPasswordToMD5();
    GeraData dataAtual = new GeraData();
    public String usuarioAtivo = "";
    MensagemErro mensagemErro = new MensagemErro();
    
    /**
     * Creates new form JanelaConfiguracao
     */
    public JanelaConfiguracao () {
        initComponents();
        super.setTitle("Configurações do Sistema");
        super.setResizable(true);  
        
        //Verifica o caminho do banco de dados salvo no caminhoBD.txt
        co.VerificaCaminhoDoBancoDeDados(co);
        
        try {
            usuarioAtivo = co.retornaUsuarioSalvoNoConfig();
        } catch (IOException ex) {
            Logger.getLogger(JanelaConfiguracao.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        //Preenche caminho do BD 
        campoDoBanco.setSelectedItem(co.retornaCaminhoBDIni(co));
       
        
        //Muda icone da Janela interna
        setFrameIcon(new ImageIcon(this.getClass().getResource(caminhoImagemIcone.getCaminho())));
                
        
        
        if(usuarioAtivo.equals("Admin")){
            campoDoBanco.setEnabled(true);
            botaoAlterarBD1.setEnabled(true);
        }
   
     
  
    }
   
    public void setPosicao() {  
        Dimension d = this.getDesktopPane().getSize();  
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);   
    }
    
 
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoDriverBD = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        campoUrlBD = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        campoUsuarioBD = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        campoSenhaBD = new javax.swing.JPasswordField();
        botaoAlterarBD = new javax.swing.JButton();
        botaoPadrao = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        botaoAlterarBD1 = new javax.swing.JButton();
        campoDoBanco = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        campoNomeExcel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNomeTabela = new javax.swing.JTextField();
        botaoImportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoNomeDasColunas = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        botaoImportar1 = new javax.swing.JButton();
        botaoImportar2 = new javax.swing.JButton();
        botaoImportar3 = new javax.swing.JButton();
        botaoSair4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        campoNomeExcel1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoNomeTabela1 = new javax.swing.JTextField();
        botaoImportar4 = new javax.swing.JButton();
        botaoImportar7 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        botaoImportar8 = new javax.swing.JButton();
        campoSeparados = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyPressed(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Configurações de BD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel7.setText("Driver:");

        campoDriverBD.setText("com.mysql.jdbc.Driver");
        campoDriverBD.setEnabled(false);

        jLabel18.setText("URL:");

        campoUrlBD.setText("jdbc:mysql://localhost:3309/BancoNovo");
        campoUrlBD.setEnabled(false);

        jLabel19.setText("Usuário:");

        campoUsuarioBD.setText("root");
        campoUsuarioBD.setEnabled(false);

        jLabel20.setText("Senha:");

        campoSenhaBD.setText("123");
        campoSenhaBD.setEnabled(false);

        botaoAlterarBD.setText("Alterar BD");
        botaoAlterarBD.setEnabled(false);
        botaoAlterarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarBDActionPerformed(evt);
            }
        });

        botaoPadrao.setText("Padrão");
        botaoPadrao.setEnabled(false);
        botaoPadrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPadraoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoUsuarioBD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoUrlBD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(campoDriverBD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoSenhaBD)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(botaoAlterarBD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPadrao)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDriverBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoUrlBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoUsuarioBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(campoSenhaBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAlterarBD)
                    .addComponent(botaoPadrao))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Configurações de Caminho de BD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel47.setText("Caminho do Banco de Dados");

        botaoAlterarBD1.setText("Alterar");
        botaoAlterarBD1.setEnabled(false);
        botaoAlterarBD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarBD1ActionPerformed(evt);
            }
        });

        campoDoBanco.setEditable(true);
        campoDoBanco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoDoBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "localhost", "diegorangel.ddns.net" }));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(botaoAlterarBD1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 146, Short.MAX_VALUE))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(botaoAlterarBD1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSair)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Configuração de BD", jPanel10);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel3KeyPressed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Importar dados do Excel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        campoNomeExcel.setEditable(false);
        campoNomeExcel.setText("\\PLANILHA_TESTE2");

        jLabel4.setText("Nome do arquivo excel  (\\*.csv)");

        jLabel5.setText("Nome da tabela");

        campoNomeTabela.setEditable(false);
        campoNomeTabela.setText("tab_produto");

        botaoImportar.setText("Importar");
        botaoImportar.setEnabled(false);
        botaoImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImportarActionPerformed(evt);
            }
        });

        campoNomeDasColunas.setEditable(false);
        campoNomeDasColunas.setColumns(10);
        campoNomeDasColunas.setLineWrap(true);
        campoNomeDasColunas.setRows(5);
        campoNomeDasColunas.setText("'\\r\\n' (codigo, produto, unid, situacao_tributaria, icm_venda, ncm, grupo, preco_fornecedor, preco_tabela, fornecedor, fabricante, quantidade_estoque, pis_confins)");
        jScrollPane1.setViewportView(campoNomeDasColunas);

        jLabel6.setText("Campos a Importar (Ex.: '\\r\\n' (codigo,nome)");

        botaoImportar1.setText("Importar código municipio");
        botaoImportar1.setEnabled(false);
        botaoImportar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImportar1ActionPerformed(evt);
            }
        });

        botaoImportar2.setText("Importar BD Jacob");
        botaoImportar2.setEnabled(false);
        botaoImportar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImportar2ActionPerformed(evt);
            }
        });

        botaoImportar3.setText("Teste");
        botaoImportar3.setEnabled(false);
        botaoImportar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoImportar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoNomeExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(campoNomeTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(botaoImportar3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoImportar2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(botaoImportar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoImportar1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNomeTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoImportar)
                    .addComponent(botaoImportar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoImportar3)
                    .addComponent(botaoImportar2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoSair4.setText("Sair");
        botaoSair4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSair4ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Importar dados do arquivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        campoNomeExcel1.setEditable(false);
        campoNomeExcel1.setText("C:\\");

            jLabel8.setText("Nome do arquivo (\\*.csv)");

            jLabel9.setText("Nome da tabela");

            campoNomeTabela1.setText("tmp_siscon_mensagens");

            botaoImportar4.setText("Importar");
            botaoImportar4.setEnabled(false);
            botaoImportar4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botaoImportar4ActionPerformed(evt);
                }
            });

            botaoImportar7.setText("Teste");
            botaoImportar7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botaoImportar7ActionPerformed(evt);
                }
            });

            jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Coluna 1", "Coluna 2", "Coluna 3"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane4.setViewportView(jTable2);
            if (jTable2.getColumnModel().getColumnCount() > 0) {
                jTable2.getColumnModel().getColumn(0).setPreferredWidth(30);
                jTable2.getColumnModel().getColumn(1).setPreferredWidth(30);
                jTable2.getColumnModel().getColumn(2).setPreferredWidth(200);
            }

            botaoImportar8.setText("Procurar");
            botaoImportar8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botaoImportar8ActionPerformed(evt);
                }
            });

            campoSeparados.setText(";");

            jLabel10.setText("Separador");

            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(campoNomeExcel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(botaoImportar8))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(campoNomeTabela1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(campoSeparados, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(botaoImportar7)
                                    .addGap(36, 36, 36)
                                    .addComponent(botaoImportar4)))
                            .addGap(0, 139, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoNomeExcel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoImportar8))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoNomeTabela1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoSeparados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaoImportar4)
                        .addComponent(botaoImportar7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoSair4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoSair4))
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(47, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("Ferramentas de Banco de dados", jPanel3);

            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String [] {
                    "Coluna 1", "Coluna 2", "Coluna 3"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane3.setViewportView(jTable1);
            if (jTable1.getColumnModel().getColumnCount() > 0) {
                jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
                jTable1.getColumnModel().getColumn(1).setPreferredWidth(30);
                jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
            }

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(160, 160, 160)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(494, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(284, Short.MAX_VALUE))
            );

            jTabbedPane1.addTab("tab3", jPanel1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void botaoAlterarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarBDActionPerformed
        //driverBD = campoDriverBD.getText();
        //urlBD = campoUrlBD.getText();
        //usuarioBD = campoUsuarioBD.getText();
        //senhaBD = campoSenhaBD.getText();
        JOptionPane.showMessageDialog(null, "Configuração de BD alterada!");
    }//GEN-LAST:event_botaoAlterarBDActionPerformed

    private void botaoPadraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPadraoActionPerformed
        campoDriverBD.setText("com.mysql.jdbc.Driver");
        campoUrlBD.setText("jdbc:mysql://localhost:3309/cadastros");
        campoUsuarioBD.setText("root");
        campoSenhaBD.setText("123");
        //driverBD = "com.mysql.jdbc.Driver";
        //urlBD = "jdbc:mysql://localhost:3309/cadastros";
        //usuarioBD = "root";
        //senhaBD = "123";
        //JOptionPane.showMessageDialog(null, "Configuração de BD padrão ativada!");
        mensagemErro.abrirAlertaDeOperacaoFeitaComSucesso("Configuração de BD padrão ativada!", "Configurado","ok");
    }//GEN-LAST:event_botaoPadraoActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImportarActionPerformed
        if (campoNomeExcel.getText().equals("")){
            //JOptionPane.showMessageDialog(null, "Digite o nome do arquivo sem a extenção!");
            mensagemErro.abrirAlertaDeOperacaoFeitaComSucesso("Digite o nome do arquivo sem a extenção!", "Falta informação","erro");
        }else{ if (campoNomeTabela.getText().equals("")){
            //JOptionPane.showMessageDialog(null, "Digite o nome da tabela!");
            mensagemErro.abrirAlertaDeOperacaoFeitaComSucesso("Digite o nome da tabela!", "Falta informação","erro");
        }else{
            i.ImportarExcelParaMysql(campoNomeExcel.getText(), campoNomeTabela.getText(), campoNomeDasColunas.getText());
        }
        }
    }//GEN-LAST:event_botaoImportarActionPerformed

    private void botaoSair4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSair4ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botaoSair4ActionPerformed

    private void jTabbedPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.setVisible(false);
        }
    }//GEN-LAST:event_jTabbedPane1KeyPressed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        //painelTabela.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        //painelTabela.setVisible(false);
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        //painelTabela.setVisible(false);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void botaoImportar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImportar1ActionPerformed
        int Confirm = JOptionPane.showConfirmDialog(null,"Importar os códigos IBGE da planilha?","Sim ou Não", JOptionPane.YES_NO_OPTION);
        if (Confirm == 0){
            i.ImportarExcelParaMysqlCodigoMunicipio();
        }
    }//GEN-LAST:event_botaoImportar1ActionPerformed

    private void botaoImportar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImportar2ActionPerformed
        i.ImportarBancoDeDados();
    }//GEN-LAST:event_botaoImportar2ActionPerformed

    private void botaoAlterarBD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarBD1ActionPerformed
        String nomeDoArquivo = "c:\\CaminhoBD.txt";
        BufferedWriter buffWrite = null; 
        String linha = ""; 
        String caminho = (String) campoDoBanco.getSelectedItem();
        if (caminho.equals("")){
            caminho = "localhost";
        }
        try {
            buffWrite = new BufferedWriter(new FileWriter(nomeDoArquivo));
            buffWrite.append(caminho+"\n");
            buffWrite.close();
            JOptionPane.showMessageDialog(null, "Caminho do banco de dados foi alterado com Sucesso para :"+caminho);
        } catch (IOException ex) {
            Logger.getLogger(JanelaConfiguracao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_botaoAlterarBD1ActionPerformed

    private void botaoImportar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImportar3ActionPerformed
        i.ImportarExcelParaMysqlMedicamentos();
    }//GEN-LAST:event_botaoImportar3ActionPerformed

    private void jPanel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel3KeyPressed
        if(evt.getKeyCode() == evt.VK_ESCAPE){
            this.setVisible(false);
        }
    }//GEN-LAST:event_jPanel3KeyPressed

    private void botaoImportar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImportar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoImportar4ActionPerformed

    private void botaoImportar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImportar7ActionPerformed
        if (campoNomeExcel1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Escolha o caminho do arquivo!");
        }else{
            if (campoSeparados.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Informe o separador!");
            }else{
                MensagemController mensagemController = new MensagemController();
                List<Mensagem> mensagens = mensagemController.loadCSV(campoNomeExcel1.getText(), campoSeparados.getText());
                if (mensagens == null){
                    JOptionPane.showMessageDialog(null, "Não foi possível ler o arquivo!");
                }else{
                    for (int i = 0; i < mensagens.size(); i++) {
                        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel)jTable2.getModel();
                        dtm.addRow(new Object[]{mensagens.get(i).getProtocolo(), mensagens.get(i).getData(), mensagens.get(i).getRecurso(),mensagens.get(i).getMensagem()}); 
                    }

                }
            }
        }
    }//GEN-LAST:event_botaoImportar7ActionPerformed

    private void botaoImportar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoImportar8ActionPerformed
        campoNomeExcel1.setText("");
        
        try {
            JFileChooser jFileChooser = new JFileChooser();
            int ok = jFileChooser.showOpenDialog(null);
            if (ok == JFileChooser.APPROVE_OPTION) {
                campoNomeExcel1.setText(jFileChooser.getCurrentDirectory().getPath() + "\\" + jFileChooser.getSelectedFile().getName()); // caminho do arquivo
                //JOptionPane.showMessageDialog(rootPane, "Caminho:"+caminho);
                //System.out.println(conteudo);
            } else {
                jFileChooser.cancelSelection();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_botaoImportar8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaConfiguracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterarBD;
    private javax.swing.JButton botaoAlterarBD1;
    private javax.swing.JButton botaoImportar;
    private javax.swing.JButton botaoImportar1;
    private javax.swing.JButton botaoImportar2;
    private javax.swing.JButton botaoImportar3;
    private javax.swing.JButton botaoImportar4;
    private javax.swing.JButton botaoImportar7;
    private javax.swing.JButton botaoImportar8;
    private javax.swing.JButton botaoPadrao;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSair4;
    public javax.swing.JComboBox<String> campoDoBanco;
    private javax.swing.JTextField campoDriverBD;
    private javax.swing.JTextArea campoNomeDasColunas;
    private javax.swing.JTextField campoNomeExcel;
    private javax.swing.JTextField campoNomeExcel1;
    private javax.swing.JTextField campoNomeTabela;
    private javax.swing.JTextField campoNomeTabela1;
    private javax.swing.JPasswordField campoSenhaBD;
    private javax.swing.JTextField campoSeparados;
    private javax.swing.JTextField campoUrlBD;
    private javax.swing.JTextField campoUsuarioBD;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
