/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.sss.View;

import br.com.sss.Control.CaminhoImagem;
import br.com.sss.Control.Clean;
import br.com.sss.Control.Conexao;
//import br.com.sss.Control.ModificaJanelaPeloPerfil;
import br.com.sss.Control.MensagemErro;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Diego Rangel  
 */
public class JanelaGradeProdutos extends javax.swing.JFrame {

    CaminhoImagem caminhoImagemIcone = new CaminhoImagem();
    Clean limpar = new Clean();
    Conexao co = new Conexao();
    public int totalDeItens = 0;
    //ModificaJanelaPeloPerfil modificaJanelaPeloPerfil = new ModificaJanelaPeloPerfil();
    MensagemErro mensagemErro = new MensagemErro();
    
    /**
     * Creates new form JanelaGradeProdutos
     */
    public JanelaGradeProdutos() {
        
        //Para deixar em FULLSCREEN ativa essas linhas abaixo
        this.setUndecorated(true);
        this.setResizable(false);
        this.setVisible(true);
        
        //Verifica o caminho do banco de dados salvo no caminhoBD.txt
        co.VerificaCaminhoDoBancoDeDados(co);
        
        initComponents();
        super.setTitle("Cadastro de Produtos");
        super.setLocationRelativeTo(null);
        super.setResizable(true);
        super.setExtendedState(super.MAXIMIZED_BOTH);
        super.setDefaultCloseOperation(super.EXIT_ON_CLOSE);
        super.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);

        //Muda icone da Janela
        URL url = this.getClass().getResource(caminhoImagemIcone.getCaminhoJanelaPrincipal());
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(imagemTitulo); 
        
        //Muda icone da Janela interna
        //setFrameIcon(new ImageIcon(this.getClass().getResource(caminhoImagemIcone.getCaminho())));
        
        campoTotalDeItens.setText(totalDeItens+"");
        campoTotal.setText("0,00");
        
//        co.atualizaFornecedorNaJanelaGradeProdutos(this);
        
    }

    public void finalizaJanela(){
        super.dispose();
    }
    
    public void limpaCampos(){
            campoCodigo.setText("");
            campoReferencia.setText("");
            campoNomeProduto.setText("");
            campoPrecoNF.setText("");
            campoPrecoVenda.setText("");
            campoQuantEstoque.setText("");
            campoQuantNF.setText("");
            campoIcm.setText("");
            campoNCM.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoNomeProduto = new javax.swing.JTextField();
        campoCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        botaoAdd = new javax.swing.JButton();
        PainelTabelaProdutos1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoTotal = new javax.swing.JFormattedTextField();
        campoTotalDeItens = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        botaoLimpar1 = new javax.swing.JButton();
        campoReferencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JLabel();
        campoPerfilPedido = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoUnidade = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        campoPis = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        campoSituacao = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        campoIcm = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        campoNCM = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        campoPrecoNF = new javax.swing.JFormattedTextField();
        campoPrecoVenda = new javax.swing.JFormattedTextField();
        campoQuantNF = new javax.swing.JFormattedTextField();
        campoQuantEstoque = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        campoFornecedor = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("Nome do produto");

        campoNomeProduto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoNomeProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNomeProdutoKeyPressed(evt);
            }
        });

        campoCodigo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoCodigoKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Cód. Produto");

        botaoAdd.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        botaoAdd.setText("Add");
        botaoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddActionPerformed(evt);
            }
        });
        botaoAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoAddKeyPressed(evt);
            }
        });

        PainelTabelaProdutos1.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos"));

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Ref.", "Produto", "Pç NF", "Pç Venda", "Quant", "Quant Est", "Unid", "PisCofins", "Sit. Trib.", "Icm Venda", "NCM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);
        if (tabelaProduto.getColumnModel().getColumnCount() > 0) {
            tabelaProduto.getColumnModel().getColumn(0).setPreferredWidth(5);
            tabelaProduto.getColumnModel().getColumn(1).setPreferredWidth(5);
            tabelaProduto.getColumnModel().getColumn(2).setPreferredWidth(200);
            tabelaProduto.getColumnModel().getColumn(3).setPreferredWidth(10);
            tabelaProduto.getColumnModel().getColumn(4).setPreferredWidth(10);
            tabelaProduto.getColumnModel().getColumn(5).setPreferredWidth(10);
            tabelaProduto.getColumnModel().getColumn(6).setPreferredWidth(10);
            tabelaProduto.getColumnModel().getColumn(7).setPreferredWidth(5);
            tabelaProduto.getColumnModel().getColumn(8).setPreferredWidth(15);
            tabelaProduto.getColumnModel().getColumn(9).setPreferredWidth(10);
            tabelaProduto.getColumnModel().getColumn(10).setPreferredWidth(10);
            tabelaProduto.getColumnModel().getColumn(11).setPreferredWidth(10);
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Cadastrar produtos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar Grade");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Total dos produtos");

        campoTotal.setEditable(false);
        campoTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        campoTotal.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        campoTotalDeItens.setEditable(false);
        campoTotalDeItens.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        campoTotalDeItens.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel2.setText("Total de ítens");

        jButton3.setText("Excluir produto da grade");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelTabelaProdutos1Layout = new javax.swing.GroupLayout(PainelTabelaProdutos1);
        PainelTabelaProdutos1.setLayout(PainelTabelaProdutos1Layout);
        PainelTabelaProdutos1Layout.setHorizontalGroup(
            PainelTabelaProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaProdutos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelTabelaProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelTabelaProdutos1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(PainelTabelaProdutos1Layout.createSequentialGroup()
                        .addGroup(PainelTabelaProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelTabelaProdutos1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoSair))
                            .addGroup(PainelTabelaProdutos1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTotalDeItens, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)))
                        .addGap(21, 21, 21))))
        );
        PainelTabelaProdutos1Layout.setVerticalGroup(
            PainelTabelaProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelTabelaProdutos1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelTabelaProdutos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(campoTotalDeItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoSair)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        botaoLimpar1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        botaoLimpar1.setText("Sair");
        botaoLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimpar1ActionPerformed(evt);
            }
        });

        campoReferencia.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoReferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoReferenciaKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("Ref. Produto");

        campoUsuario.setText("Usuário");

        campoPerfilPedido.setText("0");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("Unid");

        campoUnidade.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoUnidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UND", "UN", "MT", "M2", "M3", "LT", "KG" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("Pis Cofins");

        campoPis.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoPis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01-Oper.Trib.(base de calculo = valor da Oper.aliquota normal (cumulativo/nao cumulativo))", "02-Oper.Trib.(base de calculo = valor da Oper.(aliquota diferenciada))", "03-Oper.Trib.(base de calculo = quantidade vendida x aliquota por unidade de produto)", "04-Oper.Trib.(tributacao monofasica (aliquota zero))", "06-Oper.Trib.(aliquota zero)", "07-Oper.Isenta da Contribuicao", "08-Oper.Sem Incidencia da Contribuicao", "09-Oper.com Suspensao da Contribuicao", "99-Outras Operacoes" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("Situação tributária");

        campoSituacao.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoSituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "18%", "12%", "17%", "27%", "ISENTO", "NÃO INCIDENCIA", "REDUZIDO PARA 11%", "REDUZIDO PARA 5", "6%", "REDUZIDO PARA 7%", "REDUZIDO PARA 8", "8%", "SERVIÇO", "SUBSTITUIÇÃO TRIBUTÁRIA" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("ICM de venda");

        campoIcm.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoIcm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoIcmFocusGained(evt);
            }
        });
        campoIcm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoIcmKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("NCM");

        campoNCM.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        campoNCM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNCMKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setText("Quant");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setText("Pç NF");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("Pç Venda");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("Quant Est.");

        campoPrecoNF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        campoPrecoNF.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        campoPrecoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        campoPrecoVenda.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        campoQuantNF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        campoQuantNF.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        campoQuantEstoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        campoQuantEstoque.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setText("Fornecedor");

        campoFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        campoFornecedor.setSelectedIndex(-1);
        campoFornecedor.setSelectedItem("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainelTabelaProdutos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoReferencia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(campoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoPrecoNF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(campoQuantNF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoQuantEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(campoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(campoPis, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(campoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoIcm))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(campoNCM, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoAdd))))
                            .addComponent(jLabel18)
                            .addComponent(campoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoPerfilPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoUsuario))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoLimpar1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(5, 5, 5)
                .addComponent(campoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)))
                        .addComponent(jLabel12)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel14)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoPrecoNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoIcm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoNCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoAdd))
                    .addComponent(campoQuantNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoQuantEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelTabelaProdutos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoLimpar1)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPerfilPedido)
                    .addComponent(campoUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNomeProdutoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            campoPrecoNF.requestFocus();
        }
    }//GEN-LAST:event_campoNomeProdutoKeyPressed

    private void campoCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCodigoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            campoReferencia.requestFocus();
        }
    }//GEN-LAST:event_campoCodigoKeyPressed

    private void botaoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddActionPerformed
        if (campoNomeProduto.getText().equals("")){
            //XXXXXXXXXXXXXXXXXXXXXnull, "Digite o nome do produto a cadastrar!");
            mensagemErro.abrirAlertaDeOperacaoFeitaComSucesso("Digite o nome do produto a cadastrar!", "Falta informação","erro");
        }else{
        if (campoPrecoNF.getText().equals("")){
            //XXXXXXXXXXXXXXXXXXXXXnull, "Digite o preço do fornecedor!");
            mensagemErro.abrirAlertaDeOperacaoFeitaComSucesso("Digite o preço do fornecedor!", "Falta informação","erro");
        }else{
            javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel)tabelaProduto.getModel();
            String unid = (String) campoUnidade.getSelectedItem();
            String sit = (String) campoSituacao.getSelectedItem();
            String pis = (String) campoPis.getSelectedItem();
            String icm;
            if (campoIcm.getText().equals("")){
                icm = "0";
            }
            String precoVenda = campoPrecoVenda.getText();
            if (campoPrecoVenda.getText().equals("")){
                precoVenda = "0,00";
            }
            String quantNF = campoQuantNF.getText();
            if (campoQuantNF.getText().equals("")){
                quantNF = "0,00";
            }
            String quantEs = campoQuantEstoque.getText();
            if (campoQuantEstoque.getText().equals("")){
                quantEs = "0,00";
            }
            dtm.addRow(new Object[]{campoCodigo.getText(),campoReferencia.getText(),campoNomeProduto.getText(),campoPrecoNF.getText(),precoVenda,quantNF,quantEs,unid,pis,sit,campoIcm.getText(),campoNCM.getText()});
            limpaCampos();
            campoTotalDeItens.setText(tabelaProduto.getModel().getRowCount()+"");
//            co.atualizaTotalProdutosNaGradeCadastro(this);
        }
        }
    }//GEN-LAST:event_botaoAddActionPerformed

    private void botaoAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoAddKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            //limpar.apagaTabelaPesquisaRapida(this);
            if (campoNomeProduto.getText().equals("") && (campoCodigo.getText().equals(""))){
                //XXXXXXXXXXXXXXXXXXXXXnull, "Digite um nome ou um código de um produto!");
                mensagemErro.abrirAlertaDeOperacaoFeitaComSucesso("Digite um nome ou um código de um produto!", "Falta informação","erro");
            }else{
                //Se o código estiver preenchido
                if (!campoCodigo.getText().equals("")){
                    //Faça a pesquisa pelo código
                    //co.PesquisaProdutoRapidaPorCodigo(campoCodigo.getText(),this);
                }else{
                    //Faça a pesquisa pelo nome
                    //co.PesquisaProdutoRapidaPorNome(campoNomeProduto.getText(),this);
                }
            }
        }
    }//GEN-LAST:event_botaoAddKeyPressed

    private void botaoLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimpar1ActionPerformed
        //Chama a tela principal
        JanelaPrincipal j = new JanelaPrincipal();
        j.campoNomeUsuario.setText(campoUsuario.getText());
        String usuario = campoUsuario.getText().replace("Usuário: ","");
//        co.ativaMenuOuBotaoPeloUsuario(j, usuario);
        //co.criaArquivoUsuarioLogado(usuario);
        j.show();
        this.dispose();
    }//GEN-LAST:event_botaoLimpar1ActionPerformed

    private void campoReferenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoReferenciaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            campoNomeProduto.requestFocus();
        }
    }//GEN-LAST:event_campoReferenciaKeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.setVisible(false);
        }
    }//GEN-LAST:event_jPanel1KeyPressed

    private void campoIcmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoIcmFocusGained
        String sit = (String) campoSituacao.getSelectedItem();
        if (sit.equals("18%")){
            campoIcm.setText("18");
        }
    }//GEN-LAST:event_campoIcmFocusGained

    private void campoNCMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNCMKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            botaoAdd.requestFocus();
        }
    }//GEN-LAST:event_campoNCMKeyPressed

    private void campoIcmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoIcmKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            campoNCM.requestFocus();
        }
    }//GEN-LAST:event_campoIcmKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        limpar.apagaTabelaGradeProduto(this);
        campoTotalDeItens.setText("0");
        campoTotal.setText("0,00");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int[] l = tabelaProduto.getSelectedRows();
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel)tabelaProduto.getModel();
        for(int i = (l.length-1); i >= 0; --i)
        dtm.removeRow(l[i]);
//        co.atualizaTotalProdutosNaGradeCadastro(this);
        this.campoNomeProduto.requestFocus();
        campoTotalDeItens.setText(tabelaProduto.getModel().getRowCount()+"");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (campoTotal.getText().equals("")){
            //XXXXXXXXXXXXXXXXXXXXXnull, "Adicione produtos na grade para cadastrar!");
            mensagemErro.abrirAlertaDeOperacaoFeitaComSucesso("Adicione produtos na grade para cadastrar!", "Falta informação","erro");
        }else{
            String forn = (String) campoFornecedor.getSelectedItem();
            if (forn == "" || forn == null){
                //XXXXXXXXXXXXXXXXXXXXXnull, "Selecione o fornecedor!");
                mensagemErro.abrirAlertaDeOperacaoFeitaComSucesso("Selecione o fornecedor!", "Falta informação","erro");
            }else{
                campoTotalDeItens.setText("0");
                campoTotal.setText("0,00");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        JanelaPrincipal j = new JanelaPrincipal();
        j.campoNomeUsuario.setText(campoUsuario.getText());
        String usuario = campoUsuario.getText().replace("Usuário: ","");
        //co.criaArquivoUsuarioLogado(usuario);
        j.show();
        this.dispose();
        
        /**        
        //Chama a tela principal
        JanelaPrincipal j = new JanelaPrincipal();
        int perfil2 = Integer.parseInt(campoPerfilPedido.getText());
        j.campoPerfil.setText(perfil2+"");
        j.campoNomeUsuar    io.setText(campoUsuario.getText());
        //co.verificaPerfil(j,perfil2);
        //co.mudaPapelDeParedePeloPerfil(j,perfil2);
        //co.exibeTelaNotificacaoPeloPerfil(j,perfil2);
        j.show();
        //Encerrar a tela carregando...
        finalizaJanela();
        */       
    }//GEN-LAST:event_botaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaGradeProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaGradeProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaGradeProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaGradeProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaGradeProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel PainelTabelaProdutos1;
    private javax.swing.JButton botaoAdd;
    public javax.swing.JButton botaoLimpar1;
    private javax.swing.JButton botaoSair;
    public javax.swing.JTextField campoCodigo;
    public javax.swing.JComboBox campoFornecedor;
    public javax.swing.JTextField campoIcm;
    public javax.swing.JTextField campoNCM;
    public javax.swing.JTextField campoNomeProduto;
    public javax.swing.JLabel campoPerfilPedido;
    public javax.swing.JComboBox campoPis;
    public javax.swing.JFormattedTextField campoPrecoNF;
    public javax.swing.JFormattedTextField campoPrecoVenda;
    public javax.swing.JFormattedTextField campoQuantEstoque;
    public javax.swing.JFormattedTextField campoQuantNF;
    public javax.swing.JTextField campoReferencia;
    public javax.swing.JComboBox campoSituacao;
    public javax.swing.JFormattedTextField campoTotal;
    private javax.swing.JFormattedTextField campoTotalDeItens;
    public javax.swing.JComboBox campoUnidade;
    public javax.swing.JLabel campoUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabelaProduto;
    // End of variables declaration//GEN-END:variables
}
